site_name: "AirLab Autonomy Stack"
theme:
  name: material
  logo: assets/logo_horizontal_white.png
  favicon: assets/StackedWhite.png
  palette: 
    - scheme: default
      primary: "#CC002B"
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "#CC002B"
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.integrate
  
extra_css:
  - stylesheets/extra.css


plugins:
  - search

nav:
  - "Home": 'index.md'
  - "User Guide":
    - "Getting Started": "user_guide/getting_started.md"
    - "Installation": "user_guide/installation.md"
    - "Tutorials": "user_guide/tutorials.md"
    - "API Reference": "user_guide/api_reference.md"
  - "Developer Guide": 
    - "Developer Home": "developer_guide/dev_guide.md"
    - "Autonomy":
      - "Perception": "developer_guide/autonomy/perception.md"
      - "Mapping": "developer_guide/autonomy/mapping.md"
      - "Planning": "developer_guide/autonomy/planning.md"
      - "Navigation": "developer_guide/autonomy/navigation.md"
      - "Controls": "developer_guide/autonomy/controls.md"
    - "Simulation": "developer_guide/simulation.md"
    - "Contributing": "developer_guide/contributing.md"
  - "About": 'about.md'

repo_url: https://github.com/castacks/AirLab-Autonomy-Stack
repo_name: castacks/AirLab-Autonomy-Stack

